version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus_db:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - '9090:9090'
  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    command:      
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - '9093:9093'
  node-exporter:
    image: prom/node-exporter:v1.0.0
    container_name: node-exporter
    ports:
      - '9100:9100'
  grafana:
    image: grafana/grafana:7.0.3
    container_name: grafana
    user: "root"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=my_secret_pw
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
